QBCore.Shared.Weapons = {
	-- // 武器
	-- 近接武器
	[`weapon_unarmed`]               = { name = 'weapon_unarmed', label = '素手', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_dagger`]                = { name = 'weapon_dagger', label = 'ダガー', weapontype = '近接武器', ammotype = nil, damagereason = '刺殺 / 刺される / 内臓をえぐられる' },
	[`weapon_bat`]                   = { name = 'weapon_bat', label = 'バット', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_bottle`]                = { name = 'weapon_bottle', label = '割れたボトル', weapontype = '近接武器', ammotype = nil, damagereason = '刺殺 / 刺される / 内臓をえぐられる' },
	[`weapon_crowbar`]               = { name = 'weapon_crowbar', label = 'バール', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_flashlight`]            = { name = 'weapon_flashlight', label = '懐中電灯', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_golfclub`]              = { name = 'weapon_golfclub', label = 'ゴルフクラブ', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_hammer`]                = { name = 'weapon_hammer', label = 'ハンマー', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_hatchet`]               = { name = 'weapon_hatchet', label = '手斧', weapontype = '近接武器', ammotype = nil, damagereason = '刺殺 / 刺される / 内臓をえぐられる' },
	[`weapon_knuckle`]               = { name = 'weapon_knuckle', label = 'メリケンサック', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_knife`]                 = { name = 'weapon_knife', label = 'ナイフ', weapontype = '近接武器', ammotype = nil, damagereason = '刺殺 / 刺される / 内臓をえぐられる' },
	[`weapon_machete`]               = { name = 'weapon_machete', label = 'マチェーテ', weapontype = '近接武器', ammotype = nil, damagereason = '刺殺 / 刺される / 内臓をえぐられる' },
	[`weapon_switchblade`]           = { name = 'weapon_switchblade', label = '飛び出しナイフ', weapontype = '近接武器', ammotype = nil, damagereason = '刺殺 / 刺される / 内臓をえぐられる' },
	[`weapon_nightstick`]            = { name = 'weapon_nightstick', label = '警棒', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_wrench`]                = { name = 'weapon_wrench', label = 'レンチ', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_battleaxe`]             = { name = 'weapon_battleaxe', label = 'バトルアックス', weapontype = '近接武器', ammotype = nil, damagereason = '刺殺 / 刺される / 内臓をえぐられる' },
	[`weapon_poolcue`]               = { name = 'weapon_poolcue', label = 'プールキュー', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_briefcase`]             = { name = 'weapon_briefcase', label = 'ブリーフケース', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_briefcase_02`]          = { name = 'weapon_briefcase_02', label = 'ブリーフケース', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_garbagebag`]            = { name = 'weapon_garbagebag', label = 'ゴミ袋', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_handcuffs`]             = { name = 'weapon_handcuffs', label = '手錠', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_bread`]                 = { name = 'weapon_bread', label = 'バゲット', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打' },
	[`weapon_stone_hatchet`]         = { name = 'weapon_stone_hatchet', label = '石の手斧', weapontype = '近接武器', ammotype = nil, damagereason = '刺殺 / 刺される / 内臓をえぐられる' },
	[`weapon_candycane`]             = { name = 'weapon_candycane', label = 'キャンディケイン', weapontype = '近接武器', ammotype = nil, damagereason = '近接攻撃で殺害 / 殴打 / 処刑 / 打ちのめされる / 殺人 / 乱打 / キャンディケインで殴られる' },

	-- ハンドガン
	[`weapon_pistol`]                = { name = 'weapon_pistol', label = 'ピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_pistol_mk2`]            = { name = 'weapon_pistol_mk2', label = 'ピストル Mk2', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_combatpistol`]          = { name = 'weapon_combatpistol', label = 'コンバットピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_appistol`]              = { name = 'weapon_appistol', label = 'APピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_stungun`]               = { name = 'weapon_stungun', label = 'テーザー', weapontype = 'ピストル', ammotype = 'AMMO_STUNGUN', damagereason = '死亡' },
	[`weapon_pistol50`]              = { name = 'weapon_pistol50', label = 'ピストル .50口径', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_snspistol`]             = { name = 'weapon_snspistol', label = 'SNSピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_snspistol_mk2`]         = { name = 'weapon_snspistol_mk2', label = 'SNSピストル MK2', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_heavypistol`]           = { name = 'weapon_heavypistol', label = 'ヘビーピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_vintagepistol`]         = { name = 'weapon_vintagepistol', label = 'ヴィンテージピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_flaregun`]              = { name = 'weapon_flaregun', label = 'フレアガン', weapontype = 'ピストル', ammotype = 'AMMO_FLARE', damagereason = '死亡' },
	[`weapon_marksmanpistol`]        = { name = 'weapon_marksmanpistol', label = 'マークスマンピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_revolver`]              = { name = 'weapon_revolver', label = 'リボルバー', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_revolver_mk2`]          = { name = 'weapon_revolver_mk2', label = 'リボルバー MK2', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_doubleaction`]          = { name = 'weapon_doubleaction', label = 'ダブルアクションリボルバー', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_raypistol`]             = { name = 'weapon_raypistol', label = 'レイピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_ceramicpistol`]         = { name = 'weapon_ceramicpistol', label = 'セラミックピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_navyrevolver`]          = { name = 'weapon_navyrevolver', label = 'ネイビーリボルバー', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_gadgetpistol`]          = { name = 'weapon_gadgetpistol', label = 'ガジェットピストル', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },
	[`weapon_stungun_mp`]            = { name = 'weapon_stungun_mp', label = 'テーザー', weapontype = 'ピストル', ammotype = 'AMMO_STUNGUN', damagereason = '死亡' },
	[`weapon_pistolxm3`]             = { name = 'weapon_pistolxm3', label = 'ピストル XM3', weapontype = 'ピストル', ammotype = 'AMMO_PISTOL', damagereason = 'ピストルで撃たれる / 吹き飛ばされる / 撃ち抜かれる / キャップを外される' },

	-- サブマシンガン
	[`weapon_microsmg`]              = { name = 'weapon_microsmg', label = 'マイクロSMG', weapontype = 'サブマシンガン', ammotype = 'AMMO_SMG', damagereason = '蜂の巣にされる / 貫かれる / 仕留められる / サブマシンガンで撃たれる' },
	[`weapon_smg`]                   = { name = 'weapon_smg', label = 'SMG', weapontype = 'サブマシンガン', ammotype = 'AMMO_SMG', damagereason = '蜂の巣にされる / 貫かれる / 仕留められる / サブマシンガンで撃たれる' },
	[`weapon_smg_mk2`]               = { name = 'weapon_smg_mk2', label = 'SMG MK2', weapontype = 'サブマシンガン', ammotype = 'AMMO_SMG', damagereason = '蜂の巣にされる / 貫かれる / 仕留められる / サブマシンガンで撃たれる' },
	[`weapon_assaultsmg`]            = { name = 'weapon_assaultsmg', label = 'アサルトSMG', weapontype = 'サブマシンガン', ammotype = 'AMMO_SMG', damagereason = '蜂の巣にされる / 貫かれる / 仕留められる / サブマシンガンで撃たれる' },
	[`weapon_combatpdw`]             = { name = 'weapon_combatpdw', label = 'コンバットPDW', weapontype = 'サブマシンガン', ammotype = 'AMMO_SMG', damagereason = '蜂の巣にされる / 貫かれる / 仕留められる / サブマシンガンで撃たれる' },
	[`weapon_machinepistol`]         = { name = 'weapon_machinepistol', label = 'Tec-9', weapontype = 'サブマシンガン', ammotype = 'AMMO_PISTOL', damagereason = '蜂の巣にされる / 貫かれる / 仕留められる / サブマシンガンで撃たれる' },
	[`weapon_minismg`]               = { name = 'weapon_minismg', label = 'ミニSMG', weapontype = 'サブマシンガン', ammotype = 'AMMO_SMG', damagereason = '蜂の巣にされる / 貫かれる / 仕留められる / サブマシンガンで撃たれる' },
	[`weapon_raycarbine`]            = { name = 'weapon_raycarbine', label = 'レイカービン', weapontype = 'サブマシンガン', ammotype = 'AMMO_SMG', damagereason = '蜂の巣にされる / 貫かれる / 仕留められる / サブマシンガンで撃たれる' },

	-- ショットガン
	[`weapon_pumpshotgun`]           = { name = 'weapon_pumpshotgun', label = 'ポンプ式ショットガン', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_pumpshotgun_mk2`]       = { name = 'weapon_pumpshotgun_mk2', label = 'ポンプ式ショットガン MK2', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_sawnoffshotgun`]        = { name = 'weapon_sawnoffshotgun', label = 'ソウドオフショットガン', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_assaultshotgun`]        = { name = 'weapon_assaultshotgun', label = 'アサルトショットガン', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_bullpupshotgun`]        = { name = 'weapon_bullpupshotgun', label = 'ブルパップショットガン', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_musket`]                = { name = 'weapon_musket', label = 'マスケット銃', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_heavyshotgun`]          = { name = 'weapon_heavyshotgun', label = 'ヘビーショットガン', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_dbshotgun`]             = { name = 'weapon_dbshotgun', label = 'ダブルバレルショットガン', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_autoshotgun`]           = { name = 'weapon_autoshotgun', label = 'オートショットガン', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },
	[`weapon_combatshotgun`]         = { name = 'weapon_combatshotgun', label = 'コンバットショットガン', weapontype = 'ショットガン', ammotype = 'AMMO_SHOTGUN', damagereason = '壊滅させられる / 粉砕される / ショットガンで撃たれる' },

	-- アサルトライフル
	[`weapon_assaultrifle`]          = { name = 'weapon_assaultrifle', label = 'アサルトライフル', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_assaultrifle_mk2`]      = { name = 'weapon_assaultrifle_mk2', label = 'アサルトライフル MK2', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_carbinerifle`]          = { name = 'weapon_carbinerifle', label = 'カービンライフル', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_carbinerifle_mk2`]      = { name = 'weapon_carbinerifle_mk2', label = 'カービンライフル MK2', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_advancedrifle`]         = { name = 'weapon_advancedrifle', label = 'アドバンスライフル', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_specialcarbine`]        = { name = 'weapon_specialcarbine', label = 'スペシャルカービン', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_specialcarbine_mk2`]    = { name = 'weapon_specialcarbine_mk2', label = 'スペシャルカービン MK2', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_bullpuprifle`]          = { name = 'weapon_bullpuprifle', label = 'ブルパップライフル', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_bullpuprifle_mk2`]      = { name = 'weapon_bullpuprifle_mk2', label = 'ブルパップライフル MK2', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_compactrifle`]          = { name = 'weapon_compactrifle', label = 'コンパクトライフル', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_militaryrifle`]         = { name = 'weapon_militaryrifle', label = 'ミリタリーライフル', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },
	[`weapon_heavyrifle`]            = { name = 'weapon_heavyrifle', label = 'ヘビーライフル', weapontype = 'アサルトライフル', ammotype = 'AMMO_RIFLE', damagereason = '殺される / ライフルで撃たれる / 撃墜される / 倒される' },

	-- 軽機関銃
	[`weapon_mg`]                    = { name = 'weapon_mg', label = 'マシンガン', weapontype = '軽機関銃', ammotype = 'AMMO_MG', damagereason = 'マシンガンで撃たれる / 掃射される / 台無しにされる' },
	[`weapon_combatmg`]              = { name = 'weapon_combatmg', label = 'コンバットMG', weapontype = '軽機関銃', ammotype = 'AMMO_MG', damagereason = 'マシンガンで撃たれる / 掃射される / 台無しにされる' },
	[`weapon_combatmg_mk2`]          = { name = 'weapon_combatmg_mk2', label = 'コンバットMG MK2', weapontype = '軽機関銃', ammotype = 'AMMO_MG', damagereason = 'マシンガンで撃たれる / 掃射される / 台無しにされる' },
	[`weapon_gusenberg`]             = { name = 'weapon_gusenberg', label = 'トンプソンSMG', weapontype = '軽機関銃', ammotype = 'AMMO_MG', damagereason = 'マシンガンで撃たれる / 掃射される / 台無しにされる' },

	-- スナイパーライフル
	[`weapon_sniperrifle`]           = { name = 'weapon_sniperrifle', label = 'スナイパーライフル', weapontype = 'スナイパーライフル', ammotype = 'AMMO_SNIPER', damagereason = '狙撃される / 狙い撃ちされる / スコープで撃たれる' },
	[`weapon_heavysniper`]           = { name = 'weapon_heavysniper', label = 'ヘビースナイパー', weapontype = 'スナイパーライフル', ammotype = 'AMMO_SNIPER', damagereason = '狙撃される / 狙い撃ちされる / スコープで撃たれる' },
	[`weapon_heavysniper_mk2`]       = { name = 'weapon_heavysniper_mk2', label = 'ヘビースナイパー MK2', weapontype = 'スナイパーライフル', ammotype = 'AMMO_SNIPER', damagereason = '狙撃される / 狙い撃ちされる / スコープで撃たれる' },
	[`weapon_marksmanrifle`]         = { name = 'weapon_marksmanrifle', label = 'マークスマンライフル', weapontype = 'スナイパーライフル', ammotype = 'AMMO_SNIPER', damagereason = '狙撃される / 狙い撃ちされる / スコープで撃たれる' },
	[`weapon_marksmanrifle_mk2`]     = { name = 'weapon_marksmanrifle_mk2', label = 'マークスマンライフル MK2', weapontype = 'スナイパーライフル', ammotype = 'AMMO_SNIPER', damagereason = '狙撃される / 狙い撃ちされる / スコープで撃たれる' },
	[`weapon_remotesniper`]          = { name = 'weapon_remotesniper', label = 'リモートスナイパー', weapontype = 'スナイパーライフル', ammotype = 'AMMO_SNIPER_REMOTE', damagereason = '狙撃される / 狙い撃ちされる / スコープで撃たれる' },

	-- 重火器
	[`weapon_rpg`]                   = { name = 'weapon_rpg', label = 'RPG', weapontype = '重火器', ammotype = 'AMMO_RPG', damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_grenadelauncher`]       = { name = 'weapon_grenadelauncher', label = 'グレネードランチャー', weapontype = '重火器', ammotype = 'AMMO_GRENADELAUNCHER', damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_grenadelauncher_smoke`] = { name = 'weapon_grenadelauncher_smoke', label = 'スモークグレネードランチャー', weapontype = '重火器', ammotype = 'AMMO_GRENADELAUNCHER', damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_minigun`]               = { name = 'weapon_minigun', label = 'ミニガン', weapontype = '重火器', ammotype = 'AMMO_MINIGUN', damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_firework`]              = { name = 'weapon_firework', label = '花火ランチャー', weapontype = '重火器', ammotype = nil, damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_railgun`]               = { name = 'weapon_railgun', label = 'レールガン', weapontype = '重火器', ammotype = nil, damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_railgunxm3`]            = { name = 'weapon_railgunxm3', label = 'レールガン XM3', weapontype = '重火器', ammotype = nil, damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_hominglauncher`]        = { name = 'weapon_hominglauncher', label = 'ホーミングランチャー', weapontype = '重火器', ammotype = 'AMMO_STINGER', damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_compactlauncher`]       = { name = 'weapon_compactlauncher', label = 'コンパクトランチャー', weapontype = '重火器', ammotype = nil, damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_rayminigun`]            = { name = 'weapon_rayminigun', label = 'レイミニガン', weapontype = '重火器', ammotype = 'AMMO_MINIGUN', damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_emplauncher`]           = { name = 'weapon_emplauncher', label = 'EMPランチャー', weapontype = '重火器', ammotype = 'AMMO_EMPLAUNCHER', damagereason = '死亡' },

	-- 投擲物
	[`weapon_grenade`]               = { name = 'weapon_grenade', label = 'グレネード', weapontype = '投擲物', ammotype = nil, damagereason = '爆撃される / 爆破される / 爆発する / 吹き飛ばされる' },
	[`weapon_bzgas`]                 = { name = 'weapon_bzgas', label = 'BZガス', weapontype = '投擲物', ammotype = nil, damagereason = '死亡' },
	[`weapon_molotov`]               = { name = 'weapon_molotov', label = '火炎瓶', weapontype = '投擲物', ammotype = nil, damagereason = '火あぶりにされる / 丸焼きにされる / バーベキューにされる' },
	[`weapon_stickybomb`]            = { name = 'weapon_stickybomb', label = 'C4', weapontype = '投擲物', ammotype = nil, damagereason = '爆撃される / 爆破される / 爆発する / 吹き飛ばされる' },
	[`weapon_proxmine`]              = { name = 'weapon_proxmine', label = '近接機雷', weapontype = '投擲物', ammotype = nil, damagereason = '爆撃される / 爆破される / 爆発する / 吹き飛ばされる' },
	[`weapon_snowball`]              = { name = 'weapon_snowball', label = 'スノーボール', weapontype = '投擲物', ammotype = nil, damagereason = '死亡' },
	[`weapon_pipebomb`]              = { name = 'weapon_pipebomb', label = 'パイプ爆弾', weapontype = '投擲物', ammotype = nil, damagereason = '爆撃される / 爆破される / 爆発する / 吹き飛ばされる' },
	[`weapon_ball`]                  = { name = 'weapon_ball', label = 'ボール', weapontype = '投擲物', ammotype = 'AMMO_BALL', damagereason = '死亡' },
	[`weapon_smokegrenade`]          = { name = 'weapon_smokegrenade', label = 'スモークグレネード', weapontype = '投擲物', ammotype = nil, damagereason = '死亡' },
	[`weapon_flare`]                 = { name = 'weapon_flare', label = 'フレアピストル', weapontype = '投擲物', ammotype = 'AMMO_FLARE', damagereason = '死亡' },

	-- その他
	[`weapon_petrolcan`]             = { name = 'weapon_petrolcan', label = 'ガソリン缶', weapontype = 'その他', ammotype = 'AMMO_PETROLCAN', damagereason = '死亡' },
	[`gadget_parachute`]             = { name = 'gadget_parachute', label = 'パラシュート', weapontype = 'その他', ammotype = nil, damagereason = '死亡' },
	[`weapon_fireextinguisher`]      = { name = 'weapon_fireextinguisher', label = '消火器', weapontype = 'その他', ammotype = nil, damagereason = '死亡' },
	[`weapon_hazardcan`]             = { name = 'weapon_hazardcan', label = 'ハザード缶', weapontype = 'その他', ammotype = 'AMMO_PETROLCAN', damagereason = '死亡' },
	[`weapon_fertilizercan`]         = { name = 'weapon_fertilizercan', label = '肥料缶', weapontype = 'その他', ammotype = 'AMMO_FERTILIZERCAN', damagereason = '死亡' },
	[`weapon_barbed_wire`]           = { name = 'weapon_barbed_wire', label = '有刺鉄線', weapontype = 'その他', ammotype = nil, damagereason = '刺される' },
	[`weapon_drowning`]              = { name = 'weapon_drowning', label = '溺死', weapontype = 'その他', ammotype = nil, damagereason = '死亡' },
	[`weapon_drowning_in_vehicle`]   = { name = 'weapon_drowning_in_vehicle', label = '乗り物内での溺死', weapontype = 'その他', ammotype = nil, damagereason = '死亡' },
	[`weapon_bleeding`]              = { name = 'weapon_bleeding', label = '出血', weapontype = 'その他', ammotype = nil, damagereason = '出血死' },
	[`weapon_electric_fence`]        = { name = 'weapon_electric_fence', label = '電気フェンス', weapontype = 'その他', ammotype = nil, damagereason = '感電死' },
	[`weapon_explosion`]             = { name = 'weapon_explosion', label = '爆発', weapontype = 'その他', ammotype = nil, damagereason = '殺害される / 爆破される / 壊滅させられる / 破壊される / 消滅させられる / 全滅させられる' },
	[`weapon_fall`]                  = { name = 'weapon_fall', label = '落下', weapontype = 'その他', ammotype = nil, damagereason = '自殺' },
	[`weapon_exhaustion`]            = { name = 'weapon_exhaustion', label = '疲労', weapontype = 'その他', ammotype = nil, damagereason = '死亡' },
	[`weapon_hit_by_water_cannon`]   = { name = 'weapon_hit_by_water_cannon', label = '放水銃に当たる', weapontype = 'その他', ammotype = nil, damagereason = '死亡' },
	[`weapon_rammed_by_car`]         = { name = 'weapon_rammed_by_car', label = '車に衝突される', weapontype = 'その他', ammotype = nil, damagereason = '轢かれる / 轢かれる / 轢き殺される' },
	[`weapon_run_over_by_car`]       = { name = 'weapon_run_over_by_car', label = '車に轢かれる', weapontype = 'その他', ammotype = nil, damagereason = '轢かれる / 轢かれる / 轢き殺される' },
	[`weapon_heli_crash`]            = { name = 'weapon_heli_crash', label = 'ヘリ墜落', weapontype = 'その他', ammotype = nil, damagereason = 'ヘリコプター墜落' },
	[`weapon_fire`]                  = { name = 'weapon_fire', label = '火災', weapontype = 'その他', ammotype = nil, damagereason = '火あぶりにされる / 丸焼きにされる / バーベキューにされる' },

	-- 動物
	[`weapon_animal`]                = { name = 'weapon_animal', label = '動物', weapontype = '動物', ammotype = nil, damagereason = '襲われる' },
	[`weapon_cougar`]                = { name = 'weapon_cougar', label = 'クーガー', weapontype = '動物', ammotype = nil, damagereason = '襲われる' },
}